#!/usr/bin/env bash

tmppipe=$(mktemp -u)
mkfifo "${tmppipe}"
trap 'rm "${tmppipe}"' EXIT

# On / : Hello, world!
# On other paths: 404
function handler {
  while read -r line; do
    if [ -z "$(echo "$line" | tr -d '\r\n')" ]; then
      break
    fi

    if [[ "${line:0:10}" = "GET / HTTP" ]]; then
      echo -e "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\nHello, world!" > "${tmppipe}"
      return
    fi
  done
  echo -e "HTTP/1.1 404 NotFound\r\n\r\n\r\nNot Found" > "${tmppipe}"
}

while true; do
  tail -f "${tmppipe}" | nc -lvN "${PORT:-8080}" | handler;
done
